LINE_DELIMITER = "\n"
CMD_DELIMITER = "\n\n"

SESSION_STATUS_NEW = 0
SESSION_STATUS_RECONNETING = 1
SESSION_STATUS_CONNECTED = 2
SESSION_STATUS_CLOSING = 7
SESSION_STATUS_CLOSED = 8

SESSION_DIRECTION_INBOUND = 1
SESSION_DIRECTION_OUTBOUND = 0
